<?php
/**
 * One-time SMTP setup for FundingExpressAi.
 * Visit: https://expressfundingai.com/setup-mail.php
 * Enter the sales@ mailbox password, then DELETE this file.
 */
header('X-Content-Type-Options: nosniff');

$configPath = __DIR__ . '/mail-config.php';
$already = false;
if (is_file($configPath)) {
  $existing = include $configPath;
  if (is_array($existing) && !empty($existing['smtp_pass']) && $existing['smtp_pass'] !== 'PUT_SALES_MAILBOX_PASSWORD_HERE') {
    $already = true;
  }
}

$msg = '';
$err = '';
$ok = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$already) {
  $pass = isset($_POST['smtp_pass']) ? trim((string)$_POST['smtp_pass']) : '';
  $host = isset($_POST['smtp_host']) ? trim((string)$_POST['smtp_host']) : 'smtp.hostinger.com';
  $port = isset($_POST['smtp_port']) ? (int)$_POST['smtp_port'] : 465;
  $secure = isset($_POST['smtp_secure']) ? trim((string)$_POST['smtp_secure']) : 'ssl';
  if ($pass === '') {
    $err = 'Enter the sales@ mailbox password.';
  } else {
    $export = var_export([
      'to' => 'sales@expressfundingai.com',
      'from' => 'sales@expressfundingai.com',
      'from_name' => 'FundingExpressAi',
      'smtp_host' => $host !== '' ? $host : 'smtp.hostinger.com',
      'smtp_port' => $port > 0 ? $port : 465,
      'smtp_secure' => in_array($secure, ['ssl', 'tls'], true) ? $secure : 'ssl',
      'smtp_user' => 'sales@expressfundingai.com',
      'smtp_pass' => $pass,
      'smtp_timeout' => 30,
    ], true);
    $php = "<?php\n// Auto-generated by setup-mail.php — do not commit.\nreturn " . $export . ";\n";
    if (@file_put_contents($configPath, $php) === false) {
      $err = 'Could not write mail-config.php. Check folder permissions on public_html.';
    } else {
      require_once __DIR__ . '/smtp-mailer.php';
      $cfg = include $configPath;
      $result = fe_smtp_send($cfg, [
        'to' => $cfg['to'],
        'from' => $cfg['from'],
        'from_name' => $cfg['from_name'],
        'reply_to' => $cfg['from'],
        'subject' => 'FundingExpressAi SMTP test — success',
        'body' => "This is a test from setup-mail.php.\n\nIf you received this in sales@expressfundingai.com, SMTP is working.\n\nDELETE setup-mail.php from public_html now.",
        'attachments' => [],
      ]);
      if (!empty($result['ok'])) {
        $ok = true;
        $msg = 'SMTP works. A test email was sent to sales@expressfundingai.com. Delete setup-mail.php from public_html now.';
        $already = true;
      } else {
        $err = 'Config saved, but test send failed: ' . ($result['error'] ?? 'unknown') . '. Try smtp.titan.email or port 587 / tls if this host uses Titan Mail.';
      }
    }
  }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FundingExpressAi — Mail setup</title>
<style>
  body{font-family:Segoe UI,system-ui,sans-serif;background:#f4f7f5;color:#10231a;margin:0;padding:40px 16px;}
  .box{max-width:480px;margin:0 auto;background:#fff;border:1px solid #d7e3dc;border-radius:14px;padding:28px;box-shadow:0 10px 30px rgba(0,0,0,.06);}
  h1{font-size:1.25rem;margin:0 0 8px;}
  p{color:#5a6b63;font-size:.95rem;line-height:1.5;}
  label{display:block;font-weight:700;font-size:.85rem;margin:16px 0 6px;}
  input,select{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid #c9d6cf;border-radius:10px;font-size:1rem;}
  button{margin-top:20px;width:100%;padding:13px;border:0;border-radius:10px;background:#0B8F4E;color:#fff;font-weight:800;font-size:1rem;cursor:pointer;}
  .ok{background:#e8f7ef;color:#086138;padding:12px 14px;border-radius:10px;margin-bottom:14px;font-weight:600;}
  .err{background:#fdecec;color:#9b1c1c;padding:12px 14px;border-radius:10px;margin-bottom:14px;font-weight:600;}
  .note{font-size:.82rem;margin-top:16px;}
</style>
</head>
<body>
  <div class="box">
    <h1>Connect sales@ email (SMTP)</h1>
    <p>Hostinger blocks unreliable PHP <code>mail()</code>. Applications will send through authenticated SMTP to <strong>sales@expressfundingai.com</strong>.</p>
    <?php if ($ok && $msg): ?><div class="ok"><?php echo htmlspecialchars($msg); ?></div><?php endif; ?>
    <?php if ($err): ?><div class="err"><?php echo htmlspecialchars($err); ?></div><?php endif; ?>
    <?php if ($already && !$err): ?>
      <div class="ok">Mail is already configured. Delete <code>setup-mail.php</code> from the server for security.</div>
    <?php else: ?>
    <form method="post">
      <label for="smtp_pass">Password for sales@expressfundingai.com</label>
      <input type="password" id="smtp_pass" name="smtp_pass" required autocomplete="current-password" placeholder="Mailbox password from Hostinger Emails">

      <label for="smtp_host">SMTP host</label>
      <select id="smtp_host" name="smtp_host">
        <option value="smtp.hostinger.com">smtp.hostinger.com (Hostinger Email)</option>
        <option value="smtp.titan.email">smtp.titan.email (Titan Mail)</option>
      </select>

      <label for="smtp_port">Port</label>
      <select id="smtp_port" name="smtp_port">
        <option value="465">465 (SSL)</option>
        <option value="587">587 (TLS)</option>
      </select>

      <label for="smtp_secure">Encryption</label>
      <select id="smtp_secure" name="smtp_secure">
        <option value="ssl">ssl (use with 465)</option>
        <option value="tls">tls (use with 587)</option>
      </select>

      <button type="submit">Save &amp; send test email</button>
    </form>
    <p class="note">Use the password you set when creating the sales@ mailbox in Hostinger → Emails (not your Hostinger login password, unless they are the same).</p>
    <?php endif; ?>
  </div>
  <script>
    document.getElementById('smtp_port') && document.getElementById('smtp_port').addEventListener('change', function(){
      var sec = document.getElementById('smtp_secure');
      if (!sec) return;
      sec.value = this.value === '587' ? 'tls' : 'ssl';
    });
  </script>
</body>
</html>
